### ISSUE TITLE
Crash on Router

### ISSUE THREAD

**Issue by artig4n** [TheCrankLarson/SRVTracker#4]
I'm trying to use SRVTracker, and having some trouble figuring out some things.

I can add a location, but I don't see how to delete one, or get a list of locations I have made.

If I click Router it crashes with this:
![Screenshot 2022-01-10 072809](https://user-images.githubusercontent.com/71708959/148791979-eb5fc9a9-f381-42b6-8f03-29d24f764f07.jpg)

I'm trying to use the program for Exobiology, rather than racing. If I can get it working fully it would be very useful for tracking locations of plant life. It works as is, but since I can't delete a location it's going to fill up with stuff I no longer want.

All I really need for this is a way to store a few locations, and then delete them when I'm done. 

Thanks for the help!

**Comment by TheCrankLarson** [comment]
When did you download the release?  The error you are reporting was due to an old file creeping into the latest release, but I fixed that last night (I hope!).  Please could you download the latest release from Github and update the files from there?  It's the EDTracking.dll that will need to be replaced with a later version,

The location management is a bit funky at the moment, however, once you are able to open the Router there is an edit button in there for the location list (which allows you to add and delete them).

**Comment by TheCrankLarson** [comment]
You can also access the location editor from the Locator window.  It is the button next to the dropdown that you can use to select or add a location.

**Comment by artig4n** [comment]
I re-downloaded it just now and it no longer crashes. So thanks :)

I didn't realize the button next to the dropdown went to the location editor, because the tooltip says "Set as home (track current location)" and I believed it :)

Anyway, all good now.

**Comment by TheCrankLarson** [comment]
Ah, thanks for pointing that out.  Tooltip fixed for next version. :)
